inventory_system/inventory/urls.py
from django.urls import path
#

inventory_system/inventory_system/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reportes_generales/', include('reportes_generales.urls')),
    path('', index, name='index'),
    path('pedidos/', include('pedidos.urls')),  # Incluye las rutas de la app reportes_generales
    # Otras rutas de tus aplicaciones
]

inventory_system/pedidos/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import crear_pedido


app_name = 'pedidos'

urlpatterns = [
    path('nuevo/', crear_pedido, name='crear_pedido'),
    path('exitoso/', TemplateView.as_view(template_name="pedidos/pedido_exitoso.html"), name='pedido_exitoso'),
]

inventory_system/reportes_generales/urls.py
from django.urls import path
from . import views
from .views import reportes_generales

urlpatterns = [
    path('reportes_generales/', reportes_generales, name='reportes_generales'),
    path('ventas/', views.reporte_ventas, name='reporte_ventas'),
    path('usuarios/', views.reporte_usuarios, name='reporte_usuarios'),
    path('clientes/', views.reporte_clientes, name='reporte_clientes'),
    path('productos/', views.reporte_productos, name='reporte_productos'),
]

inventory_system/inventory/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Cliente(models.Model):
    nombre = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=150)
    email = models.EmailField(unique=True)
    telefono = models.CharField(max_length=15, null=True, blank=True)
    direccion = models.TextField(null=True, blank=True)
    fecha_registro = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.nombre} {self.apellidos}"

class Proveedor(models.Model):
    nombre = models.CharField(max_length=100)
    contacto = models.CharField(max_length=150)
    telefono = models.CharField(max_length=15)
    direccion = models.TextField()

    def __str__(self):
        return self.nombre

class Categoria(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True, null=True)
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)
    existencia = models.IntegerField(default=0)

    def __str__(self):
        return self.nombre

class Compra(models.Model):
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    fecha_compra = models.DateField(default=timezone.now)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.producto.existencia += self.cantidad
        self.producto.save()


class Venta(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    vendedor = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    def __str__(self):
        return f"Venta #{self.id} - {self.cliente}"

class DetalleVenta(models.Model):
    venta = models.ForeignKey(Venta, related_name='detalles', on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Detalle de Venta #{self.venta.id} - Producto: {self.producto.nombre}"
    
    def save(self, *args, **kwargs):
        # Actualizar la existencia del producto
        if not self.pk:  # Solo si es una nueva instancia
            self.precio = self.producto.precio_unitario
            self.producto.existencia -= self.cantidad
            self.producto.save()
        super().save(*args, **kwargs)

inventory_system/pedidos/models.py
from django.db import models

# Create your models here.

inventory_system/pedidos/forms.py
from django import forms
from inventory.models import Venta, DetalleVenta, Producto

class DetalleVentaForm(forms.ModelForm):
    class Meta:
        model = DetalleVenta
        fields = ['producto', 'cantidad', 'precio']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['producto'].queryset = Producto.objects.filter(existencia__gt=0)

class VentaForm(forms.ModelForm):
    class Meta:
        model = Venta
        fields = ['cliente']

DetalleVentaFormSet = forms.inlineformset_factory(
    Venta, DetalleVenta, form=DetalleVentaForm, extra=1, can_delete=True
)

inventory_system/inventory/views.py
from django.shortcuts import render
from .models import Venta

def lista_ventas(request):
    ventas = Venta.objects.all()
    return render(request, 'inventory/lista_ventas.html', {'ventas': ventas})

inventory_system/inventory_system/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

inventory_system/pedidos/views.py
from django.shortcuts import render, redirect
from .forms import VentaForm, DetalleVentaFormSet
from inventory.models import Venta

def crear_pedido(request):
    if request.method == 'POST':
        venta_form = VentaForm(request.POST)
        detalle_formset = DetalleVentaFormSet(request.POST)
        if venta_form.is_valid() and detalle_formset.is_valid():
            venta = venta_form.save(commit=False)
            venta.vendedor = request.user
            venta.save()
            detalles = detalle_formset.save(commit=False)
            total = 0
            for detalle in detalles:
                detalle.venta = venta
                detalle.precio = detalle.producto.precio_unitario
                total += detalle.precio * detalle.cantidad
                detalle.save()
                detalle.producto.existencia -= detalle.cantidad
                detalle.producto.save()
            venta.total = total
            venta.save()
            return redirect('index')
    else:
        venta_form = VentaForm()
        detalle_formset = DetalleVentaFormSet()
    return render(request, 'pedidos/pedido_form.html', {
        'venta_form': venta_form,
        'detalle_formset': detalle_formset
    })

inventory_system/reportes_generales/views.py
from django.shortcuts import render
from inventory.models import Venta, Cliente, Producto
from django.contrib.auth.models import User
from django.db.models import Sum, F
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def reportes_generales(request):
    return render(request, 'reportes_generales/reportes_generales.html')

def reporte_ventas(request):
    ventas = Venta.objects.annotate(
        total_detalle=Sum(F('detalles__precio') * F('detalles__cantidad'))
    )
    total_ventas = ventas.aggregate(total=Sum('total_detalle'))['total']

    context = {
        'ventas': ventas,
        'total_ventas': total_ventas,
    }
    return render(request, 'reportes_generales/reporte_ventas.html', context)

def reporte_usuarios(request):
    usuarios = User.objects.all()
    context = {
        'usuarios': usuarios
    }
    return render(request, 'reportes_generales/reporte_usuarios.html', context)

def reporte_clientes(request):
    clientes = Cliente.objects.all()
    context = {
        'clientes': clientes
    }
    return render(request, 'reportes_generales/reporte_clientes.html', context)

def reporte_productos(request):
    productos = Producto.objects.all()
    context = {
        'productos': productos
    }
    return render(request, 'reportes_generales/reporte_productos.html', context)

inventory_system/inventory_system/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página de Inicio</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #F7F8FA;
            color: #010101;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }
        .container {
            text-align: center;
        }
        .button {
            background-color: #0561FC;
            color: #FFFFFF;
            border: none;
            padding: 15px 25px;
            border-radius: 4px;
            cursor: pointer;
            font-size: 18px;
            margin: 10px;
        }
        .button:hover {
            background-color: #004bbd;
        }
        .login {
            position: absolute;
            top: 20px;
            right: 20px;
        }
        .login a {
            background-color: #93A3AB;
            color: #FFFFFF;
            border: none;
            padding: 10px 15px;
            border-radius: 4px;
            cursor: pointer;
            text-decoration: none;
        }
        .login a:hover {
            background-color: #7d8d97;
        }
    </style>
</head>
<body>
    <div class="login">
        <a href="{% url 'admin:login' %}">Login Admin</a>
    </div>
    <div class="container">
        <h1>Bienvenido a la tienda</h1>
        <a href="{% url 'pedidos:crear_pedido' %}" class="button">Realizar Pedido</a>
    </div>
</body>
</html>

inventory_system/pedidos/templates/pedidos/pedido_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Realizar Pedido</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #F7F8FA;
            color: #010101;
            margin: 0;
            padding: 0;
        }
        .container {
            width: 80%;
            margin: 0 auto;
            padding: 20px;
            background-color: #FFFFFF;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .button {
            background-color: #0561FC;
            color: #FFFFFF;
            border: none;
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
        }
        .button:hover {
            background-color: #004bbd;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Realizar Pedido</h1>
        <form method="post">
            {% csrf_token %}
            {{ venta_form.as_p }}
            <h2>Detalles del Pedido</h2>
            {{ detalle_formset.management_form }}
            {% for form in detalle_formset %}
                {{ form.as_p }}
            {% endfor %}
            <button type="submit" class="button">Realizar Pedido</button>
        </form>
    </div>
</body>
</html>

inventory_system/reportes_generales/templates/reportes_generales/reporte_clientes.html
<!DOCTYPE html>
<html>
<head>
    <title>Reporte de Clientes</title>
</head>
<body>
    <h1>Reporte de Clientes</h1>
    <table border="1">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Apellidos</th>
                <th>Email</th>
                <th>Teléfono</th>
                <th>Dirección</th>
            </tr>
        </thead>
        <tbody>
            {% for cliente in clientes %}
            <tr>
                <td>{{ cliente.id }}</td>
                <td>{{ cliente.nombre }}</td>
                <td>{{ cliente.apellidos }}</td>
                <td>{{ cliente.email }}</td>
                <td>{{ cliente.telefono }}</td>
                <td>{{ cliente.direccion }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

inventory_system/reportes_generales/templates/reportes_generales/reporte_productos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Reporte de Productos</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #F7F8FA;
            color: #010101;
            margin: 0;
            padding: 0;
        }
        .container {
            width: 80%;
            margin: 0 auto;
            padding: 20px;
            background-color: #FFFFFF;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            padding: 10px;
            border: 1px solid #93A3AB;
            text-align: left;
        }
        th {
            background-color: #0561FC;
            color: #FFFFFF;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Reporte de Productos</h1>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Descripción</th>
                    <th>Precio Unitario</th>
                    <th>Existencia</th>
                    <th>Categoría</th>
                </tr>
            </thead>
            <tbody>
                {% for producto in productos %}
                    <tr>
                        <td>{{ producto.id }}</td>
                        <td>{{ producto.nombre }}</td>
                        <td>{{ producto.descripcion }}</td>
                        <td>{{ producto.precio_unitario }}</td>
                        <td>{{ producto.existencia }}</td>
                        <td>{{ producto.categoria }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

inventory_system/reportes_generales/templates/reportes_generales/reporte_usuarios.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Reporte de Usuarios</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #F7F8FA;
            color: #010101;
            margin: 0;
            padding: 0;
        }
        .container {
            width: 80%;
            margin: 0 auto;
            padding: 20px;
            background-color: #FFFFFF;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            padding: 10px;
            border: 1px solid #93A3AB;
            text-align: left;
        }
        th {
            background-color: #0561FC;
            color: #FFFFFF;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Reporte de Usuarios</h1>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                </tr>
            </thead>
            <tbody>
                {% for usuario in usuarios %}
                    <tr>
                        <td>{{ usuario.id }}</td>
                        <td>{{ usuario.username }}</td>
                        <td>{{ usuario.email }}</td>
                        <td>{{ usuario.first_name }}</td>
                        <td>{{ usuario.last_name }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

inventory_system/reportes_generales/templates/reportes_generales/reporte_ventas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Reporte de Ventas</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #F7F8FA;
            color: #010101;
            margin: 0;
            padding: 0;
        }
        .container {
            width: 80%;
            margin: 0 auto;
            padding: 20px;
            background-color: #FFFFFF;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            padding: 10px;
            border: 1px solid #93A3AB;
            text-align: left;
        }
        th {
            background-color: #0561FC;
            color: #FFFFFF;
        }
        .total {
            font-weight: bold;
            font-size: 16px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Reporte de Ventas</h1>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Cliente</th>
                    <th>Vendedor</th>
                    <th>Fecha</th>
                    <th>Total de la Venta</th>
                </tr>
            </thead>
            <tbody>
                {% for venta in ventas %}
                    <tr>
                        <td>{{ venta.id }}</td>
                        <td>{{ venta.cliente }}</td>
                        <td>{{ venta.vendedor }}</td>
                        <td>{{ venta.fecha }}</td>
                        <td>{{ venta.total_detalle }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <p class="total">Total de Ventas: {{ total_ventas }}</p>
    </div>
</body>
</html>

inventory_system/reportes_generales/templates/reportes_generales/reportes_generales.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reportes Generales</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #F7F8FA;
            color: #010101;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }
        .container {
            text-align: center;
        }
        .button {
            background-color: #0561FC;
            color: #FFFFFF;
            border: none;
            padding: 15px 25px;
            border-radius: 4px;
            cursor: pointer;
            font-size: 18px;
            margin: 10px;
        }
        .button:hover {
            background-color: #004bbd;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Reportes Generales</h1>
        <a href="{% url 'reporte_usuarios' %}" class="button">Usuarios</a>
        <a href="{% url 'reporte_clientes' %}" class="button">Clientes</a>
        <a href="{% url 'reporte_ventas' %}" class="button">Ventas</a>
        <a href="{% url 'reporte_productos' %}" class="button">Productos</a>
    </div>
</body>
</html>